language: ruby
bundler_args: --without debugging
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-19mode
  - 2.0.0
  - 2.1.0
gemfile:
  - Gemfile
  - bundles/puppet_3_0.gemfile
  - bundles/puppet_2_7.gemfile
  - bundles/puppet_edge.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: bundles/puppet_edge.gemfile
    - rvm: 2.1.0
      gemfile: bundles/puppet_3_0.gemfile
    - rvm: 2.1.0
      gemfile: bundles/puppet_2_7.gemfile
